---
#=====================
#  Homebrew packages
#=====================
system_brews:
  - dockutil
system_casks: []
dockitems_to_add:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
