---
- name: Ensure localhost is configured as a virtualization host
  hosts: localhost
  roles:
    - role: baseline
      tags: baseline
    - role: virtualization_host
      tags: virtualization_host

- name: Ensure virtual lab environment for networkplus is configured
  hosts: localhost
  roles:
    - role: gns3_host
      tags: gns3_host
    - role: basebox
      tags: basebox
      vars:
        box: "debian-10.8.0"
      when: buildvms|bool
    - role: basebox
      tags: basebox
      vars:
        box: "windows-10"
      when: buildvms|bool
    - role: labenv_networkplus
      tags: labenv_networkplus
