---
- name: Ensure localhost is configured as a virtualization host
  hosts: localhost
  roles:
    - role: baseline
      tags: baseline
    - role: virtualization_host
      tags: virtualization_host

- name: Ensure virtual lab environment for rhcsa is configured
  hosts: localhost
  roles:
    - role: basebox
      tags: basebox
      vars:
        box: "centos-8.3.2011"
      when: buildvms|bool
    - role: labenv_rhcsa
      tags: labenv_rhcsa
