---
- name: Assert this host can use this role
  assert:
    that: ansible_distribution in supported_distributions
    fail_msg: "This role is not supported on your host operating system."
- name: Include host distribution specific variables
  include_vars: "{{ ansible_distribution | lower }}.yml"
- name: Ensure the Vagrantfile exists
  template:
    dest: "{{ demo_root }}/networkplus/Vagrantfile"
    src: "Vagrantfile.j2"
    mode: 0644
- name: Ensure virtual machines exist and have been added to GNS3
  include_tasks: "vagrant-vm-check.yml"
  when: buildvms
